# Generated by Django 4.2.1 on 2023-05-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0002_scenario_created_at_scenario_last_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeestate',
            name='relationship_type',
            field=models.CharField(choices=[('C', 'CLT'), ('P', 'Pessoa Jurídica'), ('E', 'Estagiário'), ('D', 'Diretor Estatutário')], default='C', max_length=1),
        ),
    ]
