# Generated by Django 4.2.1 on 2023-05-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0003_employeestate_relationship_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeestate',
            name='employee_type',
            field=models.CharField(choices=[('A', 'Ativo'), ('P', 'Projeção'), ('I', 'Inativo')], default='C', max_length=1),
        ),
    ]
