# Generated by Django 4.2.1 on 2023-05-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0004_employeestate_employee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='name',
            field=models.CharField(default='Teste', max_length=30),
        ),
    ]
