# Generated by Django 4.2.1 on 2023-05-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0005_scenario_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='inss_aliquot',
            field=models.DecimalField(decimal_places=2, default=26.8, max_digits=20),
            preserve_default=False,
        ),
    ]
